service: graphql

provider:
  name: aws
  runtime: nodejs4.3

plugins:
    - serverless-webpack

functions:
  graphql:
    handler: graphql.default
    events:
      - http:
        path: graphql
        method: get
